### ISSUE TITLE
Reconsider spdy/2

### ISSUE THREAD

**Issue by rnapier** [SlyMarbo/spdy#89]
The current approach to spdy/2 creates a lot of duplicated code that is tedious to maintain and bloats the final binary by 300k in my experiements. Nginx, Firefox and Chrome have all dropped support for spdy/2. My preference is just to delete the spdy2 package, which is a simple change.

**Comment by SlyMarbo** [comment]
Yeah, I agree. I'll make the change soon.

**Comment by SlyMarbo** [comment]
This is going to take longer than I first thought. On a related note, I'd suggest beginning to transition to HTTP/2, since SPDY is being deprecated by Google (and no doubt others) before long. Brad Fitzpatrick is working on [an official Go package](https://github.com/bradfitz/http2).

**Comment by rnapier** [comment]
I took out the spdy2 stuff in about 5 minutes. What are you running into?
I'm watching Brad's http2 package. My assumption is that it will eventually
replace this package (I'll probably migrate eventually, once it's very
solid). Any effort to make spdy talk HTTP/2 seems better put towards
helping Brad IMO.

**Comment by SlyMarbo** [comment]
Taking out SPDY/2 support shouldn't take long but updating the code to make SPDY/3 exclusive would be more involved, although it would improve the API by removing package `common`. I'm really busy at the moment but I'll make the change when I can.

**Comment by jeffyang28** [comment]
>> Nginx, Firefox and Chrome have all dropped support for spdy/2. 
>> My preference is just to delete the spdy2 package, which is a simple change.
I don't think so. Not all users will update their browser to the latest version. 
We have observed that there are still about 25% spdy2 connection from the user traffic.
The server should support spdy2 unless the share of spdy2 can be ignored.

**Comment by SlyMarbo** [comment]
Thanks for the input, I'm happy to sideline the removal for now.
