### ISSUE TITLE
Panic to close a running ResponseStream

### ISSUE THREAD

**Issue by jeffyang28** [SlyMarbo/spdy#95]
It' s not safe to close a running ResponseStream.

ResponseStream.Close() will set header field to nil, but header feild may be concurrently accessed by the ResponseStream.Run() which is executed in another goroutine. 

The defer/recover pattern does not slove that problem, and may cause resource leaking.

**Comment by jeffyang28** [comment]
How to gracefully close a connection is not a simple task, I think it should be redisgned.

**Comment by SlyMarbo** [comment]
Thanks for the help
